"""empty message

Revision ID: 2f16f237cd71
Revises: 
Create Date: 2024-12-09 23:29:36.280819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f16f237cd71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minio_metadata',
    sa.Column('bucket', sa.TEXT(), nullable=False),
    sa.Column('file_name', sa.TEXT(), nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name')
    )
    op.create_table('task',
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('INITIAL', 'PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED', name='taskstatus'), nullable=False),
    sa.Column('source_file_metadata_id', sa.BIGINT(), nullable=False),
    sa.Column('result_file_metadata_id', sa.BIGINT(), nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['result_file_metadata_id'], ['minio_metadata.id'], ),
    sa.ForeignKeyConstraint(['source_file_metadata_id'], ['minio_metadata.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_uuid'),
    sa.UniqueConstraint('result_file_metadata_id'),
    sa.UniqueConstraint('source_file_metadata_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('minio_metadata')
    # ### end Alembic commands ###
