"""empty message

Revision ID: 3eb175892395
Revises: a0a146480f0a
Create Date: 2025-05-07 16:53:18.820358

"""
from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = '3eb175892395'
down_revision = 'a0a146480f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='taskstatus',
        new_values=['INITIAL', 'PENDING', 'IN_PROGRESS', 'SUCCESS', 'INVALID_INPUT', 'FAILED'],
        affected_columns=[TableReference(table_schema='public', table_name='task', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='taskstatus',
        new_values=['INITIAL', 'PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED'],
        affected_columns=[TableReference(table_schema='public', table_name='task', column_name='status')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
