"""empty message

Revision ID: 3ca2531f4d6c
Revises: 0c5c4286900c
Create Date: 2025-03-16 02:26:03.955211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ca2531f4d6c'
down_revision = '0c5c4286900c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    tokentype = postgresql.ENUM('ACCESS', 'REFRESH', name='tokentype')
    op.create_table('tokens',
    sa.Column('token', sa.TEXT(), nullable=False),
    sa.Column('type', tokentype, nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    postgresql.ENUM('ACCESS', 'REFRESH', name='tokentype').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
