"""empty message

Revision ID: 34f086d0943f
Revises: 61f7dbf11d39
Create Date: 2025-01-09 23:25:14.759934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34f086d0943f'
down_revision = '61f7dbf11d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_user_id_key', 'task', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('task_user_id_key', 'task', ['user_id'])
    # ### end Alembic commands ###
