"""empty message

Revision ID: a0a146480f0a
Revises: c2824906dbd3
Create Date: 2025-04-20 02:33:14.966994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0a146480f0a'
down_revision = 'c2824906dbd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mesh_metadata',
    sa.Column('skin_color_hex', sa.TEXT(), nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task', sa.Column('mesh_metadata_id', sa.BIGINT(), nullable=True))
    op.alter_column('task', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_unique_constraint(None, 'task', ['mesh_metadata_id'])
    op.create_foreign_key(None, 'task', 'mesh_metadata', ['mesh_metadata_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='unique')
    op.alter_column('task', 'user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('task', 'mesh_metadata_id')
    op.drop_table('mesh_metadata')
    # ### end Alembic commands ###
