"""empty message

Revision ID: 61f7dbf11d39
Revises: 
Create Date: 2025-01-02 23:27:04.313424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61f7dbf11d39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minio_metadata',
    sa.Column('bucket', sa.TEXT(), nullable=False),
    sa.Column('file_name', sa.TEXT(), nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name')
    )
    op.create_table('user',
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('hashed_password', sa.TEXT(), nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('hashed_password')
    )
    taskstatus = postgresql.ENUM('INITIAL', 'PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED', name='taskstatus')
    op.create_table('task',
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('status', taskstatus, nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('source_file_metadata_id', sa.BIGINT(), nullable=False),
    sa.Column('result_file_metadata_id', sa.BIGINT(), nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('dt_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('dt_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['result_file_metadata_id'], ['minio_metadata.id'], ),
    sa.ForeignKeyConstraint(['source_file_metadata_id'], ['minio_metadata.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_uuid'),
    sa.UniqueConstraint('result_file_metadata_id'),
    sa.UniqueConstraint('source_file_metadata_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('user')
    op.drop_table('minio_metadata')
    postgresql.ENUM('INITIAL', 'PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED', name='taskstatus').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
