basePath: /3d-avatar/api
definitions:
  dtos.GetTaskStatusResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  dtos.UploadInputImageResponse:
    properties:
      message:
        type: string
      request_uuid:
        type: string
    type: object
info:
  contact: {}
  license:
    name: Apache 2.0
  title: 3D Avatar API
  version: "1.0"
paths:
  /v1//3d-model-generation/task/:id/status:
    get:
      consumes:
      - application/json
      operationId: 3d-model-generation-get-result-file
      parameters:
      - description: UUID of task generated after uploading input image
        in: path
        name: id
        required: true
        type: string
      produces:
      - model/gltf-binary
      responses:
        "200":
          description: OK
          schema:
            type: file
      summary: Get result .glb file
  /v1/3d-model-generation/input-image:
    post:
      consumes:
      - multipart/form-data
      operationId: 3d-model-generation-post-input-image
      parameters:
      - description: Input image
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.UploadInputImageResponse'
      summary: Upload input image for generating 3d model
swagger: "2.0"
